version: 2.0
orbs:
  cypress: cypress-io/cypress@1.0.0

jobs:
  install:
    working_directory: ~/github-reporter

    docker:
      - image: circleci/node:12.9.1-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - persist_to_workspace:
          root: ~/github-reporter
          paths: ./node_modules

      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    working_directory: ~/github-reporter

    docker:
      - image: circleci/node:12.9.1-browsers

    steps:
      - checkout

      - attach_workspace:
          at: ~/github-reporter

      - run:
          name: Build
          command: npm run build

  lint:
    working_directory: ~/github-reporter

    docker:
      - image: circleci/node:12.9.1-browsers

    steps:
      - checkout

      - attach_workspace:
          at: ~/github-reporter

      - run:
          name: Linting
          command: npm run lint

  cypress/run

  deploy:
    working_directory: ~/github-reporter

    docker:
      - image: circleci/node:12.9.1-browsers

    steps:
      - checkout

      - attach_workspace:
          at: ~/github-reporter

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: Deploy & Alias
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npm run ci:deploy:production
              elif [ "${CIRCLE_BRANCH}" == "stage" ]; then
                  npm run ci:deploy:staging
              else
                  npm run ci:deploy:feature
              fi

workflows:
  version: 2
  build:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - cypress/run
      - deploy:
          requires:
            - build
            - lint
            - cypress/run
          filters:
            branches:
              only:
                - develop
                - master
                - stage