version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Linting
          command: npm run lint

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

      - run:
          name: "What token?"
          command: echo ${ZEIT_TOKEN}

      - deploy:
          name: Deploy & Alias
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  now -p --force --no-clipboard -t ${ZEIT_TOKEN}
              fi