version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/github-reporter

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Linting
          command: npm run lint --max-warnings=5

      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now

  deploy:
    docker:
      - image: circleci/node:12.9.1-browsers

    steps:
      - run:
          name: Deploy & Alias
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  now --token $ZEIT_TOKEN --prod --confirm
              fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master