version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                now --token $ZEIT_TOKEN --local-config .now/now.production.json
                now --token $ZEIT_TOKEN --local-config .now/now.production.json alias
            fi
